# jenkins job 配置文件
# 可以通过在 commit 中添加 prefix ，使 CI 出发 jenkins job 的创建/构建行为
# 提交 commit 信息
# [jb] XXXXXX 执行 jenkins job ，如果不存在 job ，则会在对应 job_view 下创建并执行
#
########################
#         选填
########################
# job 参数
# 添加自己的钉钉消息等健值对
# 需要注意的是，这里面的配置，模版必须已经存在了，这里只是修改对应的值
parameters:
  REPORTER_ACCESS_TOKEN: XXXXXX
  DEBUG: true

########################
#         必填
########################
# 打包 job 名称 / 前缀名
# 如果 job_name 为空，则采用 job_name_prefix + 分支名称
# job_name: XXXX
job_name_prefix: ZGiOS_
# jenkins 上的分组，对应 view
job_view: 掌柜iOS

# jenkins 用户名密码
username: qingmu
password: 1


branch: feature/jenkins-executer
remote_url: git@git.2dfire-inc.com:ios/restapp.git
# credentials_id: xxx

# 各业务线采用不同的模版，配置这里
# 模版工程名称（需要唯一）
template_job_name: ZGiOS_develop

# 这里不动
server_url: 'http://jenkins-shopkeeper-client.2dfire.net'
server_port: 80